services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bibliothek
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres"]
        interval: 10s
        timeout: 5s
        retries: 5

  backend:
    build:
      context: ./bibliothek-backend
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/bibliothek
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      JWT_SECRET: bibliothek-secret-key
      FRONTEND_URL: http://localhost:4200/
    ports:
      - "8080:8080"
    depends_on:
      - db

  frontend:
    build:
      context: ./bibliothek-frontend
    ports:
      - "4200:80"
    depends_on:
      - backend

volumes:
  db-data:
